name: neurogram-dev

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: neuro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neurogram
    ports:
      - "5445:5432" # доступ с хоста (ноута)
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - dev

  base:
    profiles: ["workers"]
    build:
      context: ../..
      dockerfile: app/workers/base/Dockerfile
      target: dev
    container_name: neuro-base
    volumes:
      - ../../app:/app
      - uv-venv-base:/app/.venv # отдельный том под venv worker
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
      - UV_LINK_MODE=copy
    command: ["uv", "run", "python", "-m", "workers.base"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - s3
      - web

  dialog:
    profiles: ["workers"]
    build:
      context: ../..
      dockerfile: app/workers/dialog/Dockerfile
      target: dev
    container_name: neuro-dialog
    volumes:
      - ../../app:/app
      - uv-venv-dialog:/app/.venv # отдельный том под venv worker
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
      - UV_LINK_MODE=copy
    command: ["uv", "run", "python", "-m", "workers.dialog"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - s3
      - web

  api:
    build:
      context: ../..
      dockerfile: app/api/Dockerfile
      target: dev
    container_name: neuro-api
    ports:
      - "8833:8833" # маппим наружу API
    volumes:
      - ../../app:/app
      - uv-venv-api:/app/.venv # отдельный том под venv api
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["uv", "run", "python", "-m", "api.dev"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - s3
      - web

  web:
    build:
      context: ../../web
      target: dev
    container_name: neuro-web
    ports:
      - "5173:5173"
    volumes:
      - ../../web:/app
      - /app/node_modules
      - ./config.yml:/app/config.yml
    depends_on:
      - api
    networks:
      - dev
      - web

volumes:
  uv-venv-base: {}
  uv-venv-dialog: {}
  uv-venv-api: {}
  postgres-data-dev: {}

networks:
  hatchet:
    external: true
    name: hatchet-network
  web:
    driver: bridge
  dev:
    driver: bridge
  s3:
    external: true
    name: neuro-s3-dev
