services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: neuro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neurogram
    ports:
      - "5445:5432" # доступ с хоста (ноута)
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - dev

  base-worker:
    build:
      context: ../../workers/base
      target: dev
    container_name: neuro-base-worker
    volumes:
      - ../../workers/base:/app
      - uv-venv-base-worker:/app/.venv # отдельный том под venv worker
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
      - UV_LINK_MODE=copy
    command: ["uv", "run", "python", "-m", "app"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - web

  dialog-worker:
    build:
      context: ../../workers/dialog
      target: dev
    container_name: neuro-dialog-worker
    volumes:
      - ../../workers/dialog:/app
      - uv-venv-dialog-worker:/app/.venv # отдельный том под venv worker
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
      - UV_LINK_MODE=copy
    command: ["uv", "run", "python", "-m", "app"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - web

  api:
    build:
      context: ../../api
      target: dev
    container_name: neuro-api
    ports:
      - "8833:8833" # маппим наружу API
    volumes:
      - ../../api:/app
      - uv-venv-api:/app/.venv # отдельный том под venv api
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
    command: ["uv", "run", "python", "-m", "app.dev"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - web

  web:
    build:
      context: ../../web
      target: dev
    container_name: neuro-web
    ports:
      - "5173:5173"
    volumes:
      - ../../web:/app
      - /app/node_modules
      - ./config.yml:/app/config.yml
    depends_on:
      - api
      - base-worker
    networks:
      - dev
      - web

  minio:
    build:
      context: ./minio
    container_name: neuro-minio
    environment:
      MINIO_ROOT_USER: mike
      MINIO_ROOT_PASSWORD: gabun8374
      S3_ACCESS_KEY: "IhDRQQH1TfL0wQtUDpKV"
      S3_SECRET_KEY: "G2J10kVTv3E6eBMHOcmnQIrM00fqwa3fFpqCs49g"

    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - dev
      - web

volumes:
  uv-venv-base-worker: {}
  uv-venv-dialog-worker: {}
  uv-venv-api: {}
  postgres-data-dev: {}
  minio-data: {}

networks:
  hatchet:
    external: true
    name: hatchet-network
  web:
    driver: bridge
  dev:
    driver: bridge
