# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-02-13 22:54:49
# ============================================================

__generated__ = True


from pydantic import BaseModel

class DialogIn(BaseModel):
    account_id: int
    recipients_id: list[int]
    key: str
