# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-02-13 22:54:49
# ============================================================

__generated__ = True


from . import models
from api.hatchet.client import hatchet

dialog = hatchet.stubs.task(
    name="dialog",
    input_validator=models.DialogIn,
)
