# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-11 20:24:14
# ============================================================

__generated__ = True
import re

from aiopath import AsyncPath

from app.common.models.enums import DialogStatus

PROMPT_TITLES = {
    "role": "РОЛЬ",
    "instruction": "ИНСТРУКЦИЯ",
    "context": "КОНТЕКСТ",
    "init": "STAGE 1: INIT",
    "engage": "STAGE 2: ENGAGE",
    "offer": "STAGE 3: OFFER",
    "closing": "STAGE 4: CLOSING",
    "rules": "ГЛОБАЛЬНЫЕ ПРАВИЛА",
}


def get_ooc_status(message: str) -> DialogStatus | None:
    match = re.search(r"STATUS:\s*(init|engage|offer|closing)", message)
    if match:
        status = match.group(1)
        return DialogStatus(status)


def strip_ooc_status(message: str) -> str:
    return re.sub(r"STATUS:.*", "", message).strip()


async def get_status_addon() -> str:
    return await AsyncPath("app/common/utils/prompts/status_addon.txt").read_text()


async def build_prompt(prompt: dict, status: DialogStatus = DialogStatus.INIT):
    text = []
    statuses = {s.value for s in DialogStatus}
    for key, title in PROMPT_TITLES.items():
        if key not in statuses:
            block = f"# {title}\n{prompt[key]}"
            text.append(block)
        elif key == status:
            block = f"# {title}\n{prompt[key]}"
            text.append(block)

    markdown = "\n\n".join(text)
    markdown = markdown.replace("{current_status}", status.value)
    return markdown
