# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-10-23 23:15:03
# ============================================================

__generated__ = True
import asyncio
import re

from aiopath import AsyncPath
from html_to_markdown import convert

from app.common.models.enums import DialogStatus

PROMPT_DATA = {
    "first_message": {
        "file": "00-first-message.txt",
    },
    "role": {
        "file": "10-role.html",
        "title": "РОЛЬ",
    },
    "instruction": {
        "file": "20-instruction.html",
        "title": "ИНСТРУКЦИЯ",
    },
    "context": {
        "file": "30-context.html",
        "title": "КОНТЕКСТ",
    },
    "init": {
        "file": "41-init.html",
        "title": "STAGE 1: INIT",
    },
    "engage": {
        "file": "42-engage.html",
        "title": "STAGE 2: ENGAGE",
    },
    "offer": {
        "file": "43-offer.html",
        "title": "STAGE 3: OFFER",
    },
    "closing": {
        "file": "44-closing.html",
        "title": "STAGE 4: CLOSING",
    },
    "transitions": {
        "file": "50-transitions.html",
        "title": "СИСТЕМА ПЕРЕХОДОВ МЕЖДУ STAGE",
    },
    "rules": {
        "file": "60-rules.html",
        "title": "ГЛОБАЛЬНЫЕ ПРАВИЛА ",
    },
}

CONST_BLOCKS = ["transitions"]


async def get_default_prompt():
    params = {}
    for key in PROMPT_DATA:
        if key not in CONST_BLOCKS:
            params[key] = (
                await AsyncPath("app/prompt")
                .joinpath(PROMPT_DATA[key]["file"])
                .read_text()
            )
    return params


async def get_const_blocks():
    params = {}
    for key in CONST_BLOCKS:
        params[key] = (
            await AsyncPath("app/prompt").joinpath(PROMPT_DATA[key]["file"]).read_text()
        )
    return params


def get_ooc_status(message: str) -> DialogStatus:
    match = re.search(r"OOC_STATUS:\s*(init|engage|offer|closing)", message)
    if match:
        status = match.group(1)
        return DialogStatus(status)
    else:
        return DialogStatus.INIT


def strip_ooc_status(message: str) -> str:
    return re.sub(r"OOC_STATUS:.*", "", message).strip()


STATUS_ADDON = """
# Текущий статус диалога: {current_status}

После ответа выполни OOC-анализ (вне контекста):

- Проверь, достигнута ли цель текущего статуса {current_status} на основе всего диалога.
- Если цель достигнута — верни новый статус (следующий по порядку: init -> engage -> offer -> closing).
- Если нет — верни текущий статус.
- Добавь в конец ответа строку: OOC_STATUS: [статус]

Пример: Если в init ты поприветствовал и задал вопрос, а пользователь ответил — цель достигнута, верни engage.
"""


def get_status_addon(status: DialogStatus) -> str:
    return STATUS_ADDON.replace("{current_status}", status.value)


async def build_prompt(prompt: dict, status: DialogStatus = DialogStatus.INIT):
    html = []
    statuses = {s.value for s in DialogStatus}

    for key, data in PROMPT_DATA.items():
        if key in ["first_message"]:
            continue
        if key not in statuses:
            title = f"<h1>{data['title']}</h1>" if "title" in data else ""
            block = f"{title}{prompt[key]}"
            html.append(block)
        elif key == status:
            block = (
                f"<h1>{data['title']}</h1><p>=== СТАТУС СИСТЕМЫ ===</p>{prompt[key]}"
            )
            html.append(block)

    markdown = await asyncio.to_thread(convert, "<hr>".join(html))
    markdown = markdown.replace("{current_status}", status.value)
    return markdown
