# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-11-15 17:08:24
# ============================================================

__generated__ = True
from typing import Any

import aioboto3
from botocore.client import Config

from app.common.utils.functions import chunk_by_size
from app.config import config


class AsyncS3Client:
    _client: Any

    def __init__(self, public=False):
        self.access_key = config.s3.access_key
        self.secret_key = config.s3.secret_key

        self.endpoint_url = (
            config.s3.endpoint_url if not public else config.s3.public_endpoint_url
        )
        self._session = aioboto3.Session()
        self._client = None

    async def __aenter__(self):
        self._client = await self._session.client(
            "s3",
            aws_access_key_id=self.access_key,
            aws_secret_access_key=self.secret_key,
            endpoint_url=self.endpoint_url,
            config=Config(signature_version="s3v4"),
        ).__aenter__()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self._client:
            await self._client.__aexit__(exc_type, exc_val, exc_tb)

    def ensure_client_and_parse_path(self, path: str) -> tuple[str, str]:
        if not self._client:
            raise RuntimeError("S3 client not initialized. Use 'async with'")
        path = path.strip("/")
        segments = path.split("/", 1)
        if len(segments) == 1:
            raise ValueError(f"invalid path {path}")
        bucket, key = segments
        return bucket, key

    async def put(self, path: str, data: bytes, content_type: str | None = None):
        bucket, key = self.ensure_client_and_parse_path(path)
        kwargs = dict(Bucket=bucket, Key=key, Body=data)
        if content_type:
            kwargs["ContentType"] = content_type
        await self._client.put_object(**kwargs)

    async def delete(self, path: str):
        bucket, key = self.ensure_client_and_parse_path(path)
        await self._client.delete_object(Bucket=bucket, Key=key)

    async def delete_many(self, paths: list[str]):
        bucket_keys = [self.ensure_client_and_parse_path(p) for p in paths]
        buckets: dict[str, list[str]] = {}
        for bucket, key in bucket_keys:
            buckets.setdefault(bucket, []).append(key)
        try:
            for bucket, keys in buckets.items():
                for chunk in chunk_by_size(keys, 1000):
                    await self._client.delete_objects(
                        Bucket=bucket,
                        Delete={"Objects": [{"Key": k} for k in chunk]},
                    )
        except:
            pass

    async def get(self, path: str) -> bytes:
        bucket, key = self.ensure_client_and_parse_path(path)
        resp = await self._client.get_object(Bucket=bucket, Key=key)
        async with resp["Body"] as stream:
            return await stream.read()

    async def presigned_put_url(
        self, path: str, expires_in: int = 3600, meta: dict | None = None
    ):
        bucket, key = self.ensure_client_and_parse_path(path)
        return await self._presigned_url(bucket, key, "put_object", expires_in, meta)

    async def presigned_get_url(
        self, path: str, expires_in: int = 3600, meta: dict | None = None
    ):
        bucket, key = self.ensure_client_and_parse_path(path)
        return await self._presigned_url(bucket, key, "get_object", expires_in, meta)

    async def _presigned_url(
        self,
        bucket: str,
        key: str,
        method: str,
        expires_in: int = 3600,
        meta: dict[str, Any] | None = None,
    ) -> str:
        print(bucket, key, method)
        params = {"Bucket": bucket, "Key": key}
        if meta:
            params["Metadata"] = {k: str(v) for k, v in meta.items()}  # type: ignore

        return await self._client.generate_presigned_url(
            ClientMethod=method,
            Params=params,
            ExpiresIn=expires_in,
        )
