# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-09-21 21:16:42
# ============================================================

__generated__ = True
import ast
import os
from typing import Self

from dotenv import dotenv_values
from pydantic import BaseModel


def smart_parse(value):
    if not isinstance(value, str):
        return value
    val = value.strip()
    if val.isdigit() or (val.startswith("-") and val[1:].isdigit()):
        try:
            return int(val)
        except Exception:
            pass
    try:
        f = float(val)
        return f
    except Exception:
        pass
    lowered = val.lower()
    if lowered in {"true", "yes", "on"}:
        return True
    if lowered in {"false", "no", "off"}:
        return False
    if (
        (val.startswith("[") and val.endswith("]"))
        or (val.startswith("{") and val.endswith("}"))
        or (val.startswith("(") and val.endswith(")"))
    ):
        try:
            return ast.literal_eval(val)
        except Exception:
            pass
    return value


class BaseSettings(BaseModel):
    @classmethod
    def from_env_file(cls, env_path: str = ".env") -> Self:
        env_vars = dotenv_values(env_path)
        result = {}

        for key, value in env_vars.items():
            if "_" not in key:
                continue
            outer, inner = key.split("_", 1)
            outer = outer.lower()
            inner = inner.lower()

            actual_value = os.environ.get(key, value)
            actual_value = smart_parse(actual_value)

            if outer not in result:
                result[outer] = {}

            result[outer][inner] = actual_value

        return cls(**result)
