import tomllib
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Self

from pydantic import BaseModel, ValidationError
from rich import print

header = f"""# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# ============================================================

__generated__ = True
"""


class SyncConfig(BaseModel):
    """
    Minimal config for stub/model codegen.

    Codegen runs for all subfolders in ./workers by default.
    """

    workers_dir: Path = Path("workers")
    output_root: Path = Path("api/hatchet")
    client_import: str = "from api.hatchet.client import hatchet"
    include: list[str] | None = None
    exclude: list[str] = []

    @classmethod
    def load(cls, path: str | Path = "pyproject.toml") -> Self:
        with open(path, "rb") as f:
            data = tomllib.load(f)
        try:
            return cls(**(data.get("tool", {}).get("sync", {}) or {}))
        except ValidationError as e:
            print("❌ Ошибка валидации секции [tool.sync]:")
            for err in e.errors():
                loc = ".".join(str(x) for x in err["loc"])
                msg = err["msg"]
                print(f"  • {loc}: {msg}")
            raise SystemExit(1)


class CodegenConfig(BaseModel):
    worker: str
    tasks_package: str
    output_dir: Path
    client_import: str
    header: str = header


@dataclass
class TaskData:
    name: str
    input_model: type[Any] | None
    output_model: type[Any] | None


@dataclass
class WorkflowData:
    name: str
    input_model: type[Any] | None


@dataclass
class StubsData:
    tasks: list[TaskData]
    workflows: list[WorkflowData]
