# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-22 21:39:52
# ============================================================

__generated__ = True
import json
import random
from dataclasses import asdict, dataclass
from typing import Any, Optional, Self

import phonenumbers  # type: ignore
from aiopath import AsyncPath
from telethon import TelegramClient  # type: ignore
from telethon.sessions import MemorySession, StringSession  # type: ignore

from app.common.models import orm


@dataclass
class AccountFile:
    session: AsyncPath
    json: AsyncPath


@dataclass
class AccountIn:
    id: int
    user_id: int
    proxy_id: int
    session: str
    premium: bool
    username: str | None
    first_name: str | None
    last_name: str | None
    channel: str | None
    about: str | None


CFG = {
    "id": 2040,
    "app_hash": "b18441a1ff607e10a989891a5462e627",
    "key_map": {
        "app_id": ["app_id", "api_id"],
        "app_hash": ["app_hash", "api_hash"],
        "twofa": [
            "twoFA",
            "password",
            "twostep",
            "password2FA",
            "twofa",
            "password2fa",
        ],
        "device_model": ["device"],
        "system_version": ["sdk"],
        "app_version": ["app_version"],
    },
    "system": {
        "Windows PC": ["Windows 10", "Windows 11"],
        "Linux PC": ["Ubuntu 20.04", "Ubuntu 22.04", "Debian 12", "Arch Linux"],
        "MacBook Pro": ["macOS 12 Monterey", "macOS 13 Ventura", "macOS 14 Sonoma"],
    },
    "version": ["4.15.0 x64", "4.14.3 x64", "4.13.1 x64", "4.12.2 x64"],
}


@dataclass
class AccountUtil:
    app_id: int
    app_hash: str
    device_model: str
    system_version: str
    app_version: str
    twofa: str
    country: str
    phone: str
    session_file: Optional[AsyncPath] = None
    session_string: Optional[str] = None
    memory_session: bool = False

    def __post_init__(self):
        if not (self.session_file or self.session_string):
            raise ValueError("Нужно указать session_file или session_string")
        if self.session_file and self.session_string:
            raise ValueError(
                "Нельзя указывать одновременно session_file и session_string"
            )

    def create_client(self, proxy: orm.Proxy) -> TelegramClient:
        params = {
            "api_hash": self.app_hash,
            "api_id": self.app_id,
            "device_model": self.device_model,
            "app_version": self.app_version,
            "system_version": self.system_version,
            "session": StringSession(self.session_string)
            if self.session_string
            else str(self.session_file),
            "proxy": {
                "proxy_type": 2,  # socks5
                "addr": proxy.host,
                "port": proxy.port,
                "username": proxy.username,
                "password": proxy.password,
                "rdns": True,
            },
        }
        if self.memory_session:
            params["session"] = MemorySession()
        return TelegramClient(**params)

    def to_orm(self, account: AccountIn) -> orm.Account:
        params = {
            "app_id": self.app_id,
            "app_hash": self.app_hash,
            "twofa": self.twofa,
            "country": self.country,
            "device_model": self.device_model,
            "system_version": self.system_version,
            "app_version": self.app_version,
            "phone": self.phone,
            "id": account.id,
            "first_name": account.first_name,
            "last_name": account.last_name,
            "username": account.username,
            "premium": account.premium,
            "user_id": account.user_id,
            "session": account.session,
            "about": account.about,
            "channel": account.channel,
        }
        return orm.Account(**params)

    @classmethod
    def from_orm(cls, orm_account: orm.Account) -> Self:
        params = {
            "app_id": orm_account.app_id,
            "app_hash": orm_account.app_hash,
            "twofa": orm_account.twofa,
            "country": orm_account.country,
            "device_model": orm_account.device_model,
            "system_version": orm_account.system_version,
            "app_version": orm_account.app_version,
            "phone": orm_account.phone,
            "session_string": orm_account.session,
        }
        return cls(**params)

    @classmethod
    async def instance(cls, file: AccountFile) -> Self:
        result: dict[str, Any] = dict()
        result["session_file"] = file.session
        result["phone"] = file.session.stem
        if not result["phone"].isdigit():
            raise ValueError("Имя файла не является номером телефона")

        phone = phonenumbers.parse(f"+{result['phone']}")
        country_code = phonenumbers.region_code_for_number(phone)
        result["country"] = country_code

        device = None

        content = await file.json.read_text()
        data = json.loads(content)

        for field, keys in CFG["key_map"].items():
            value = None
            for k in keys:
                if k in data and data[k]:
                    value = data[k]
                    break
            if not value:
                if field == "device_model":
                    device = random.choice(list(CFG["system"].keys()))
                    value = device
                elif field == "system_version":
                    if not device:
                        device = random.choice(list(CFG["system"].keys()))
                    value = random.choice(CFG["system"][device])
                elif field == "app_version":
                    value = random.choice(CFG["version"])
                elif field == "app_id":
                    value = str(CFG["app_id"])
                elif field == "app_hash":
                    value = CFG["app_hash"]

            result[field] = value

        return cls(**result)

    def model_dump(self):
        return asdict(self)
