# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-18 18:07:45
# ============================================================

__generated__ = True
from io import StringIO

import httpx

from app.common.models.orm import Account, Dialog
from app.config import config


def get_api_url(endpoint: str):
    return f"https://api.telegram.org/bot{config.api.bot.token.get_secret_value()}/{endpoint}"


async def build_dialog_text_file(dialog_id: int) -> tuple[str, str, bytes]:
    """
    Возвращает (filename, file_bytes).
    """
    dialog = (
        await Dialog.get(id=dialog_id)
        .select_related("recipient", "account")
        .prefetch_related("messages")
    )

    recipient = dialog.recipient
    account = dialog.account

    # Заголовок файла
    buf = StringIO()
    buf.write(f"Диалог #{dialog.id}\n")
    buf.write(f"Аккаунт: {account.display_username}\n")
    buf.write(f"Получатель: {recipient.username}\n")
    buf.write(f"Начат: {dialog.started_at}\n")
    buf.write(f"Завершён: {dialog.finished_at}\n")
    buf.write("\n=====================\n\n")

    # Сообщения
    msgs = sorted(dialog.messages, key=lambda m: m.created_at)

    for msg in msgs:
        author = (
            account.display_username
            if msg.sender.name == "ACCOUNT"
            else recipient.username
        )

        time = msg.created_at.strftime("%Y-%m-%d %H:%M:%S")

        buf.write(f"[{time}] {author}:\n")
        buf.write(f"{msg.text or ''}\n\n")

    filename = f"dialog_{dialog.id}.txt"
    file_bytes = buf.getvalue().encode("utf-8")

    caption = f"Новая заявка от @{recipient.username}"

    return caption, filename, file_bytes


async def notify_complete_dialog(dialog: Dialog, account: Account):
    caption, filename, content = await build_dialog_text_file(dialog.id)
    await send_file_to_user(account.user_id, filename, content, caption)


async def notify_mailing_end(user_id: int, mailing_name: str, project_name: str):
    text = f"Рассылка '{mailing_name}' проекта '{project_name}' завершена"
    await send_text_to_user(chat_id=user_id, text=text)


async def send_text_to_user(chat_id: int, text: str):
    data = {
        "chat_id": str(chat_id),
        "text": text,
    }
    async with httpx.AsyncClient() as client:
        response = await client.post(get_api_url("sendMessage"), data=data)
        response.raise_for_status()
        return response.json()


async def send_file_to_user(chat_id: int, filename: str, content: bytes, caption: str):
    files = {
        "document": (filename, content, "text/plain"),
    }
    data = {
        "chat_id": str(chat_id),
        "caption": caption,
    }
    async with httpx.AsyncClient() as client:
        response = await client.post(
            get_api_url("sendDocument"), data=data, files=files
        )
        response.raise_for_status()
        return response.json()


class BotNotify:
    @classmethod
    async def _send(cls, chat_id: int, msg: str) -> None:
        await send_text_to_user(chat_id, msg)

    @classmethod
    async def error(cls, chat_id: int, msg: str):
        await cls._send(chat_id, f"⛔ {msg}")

    @classmethod
    async def info(cls, chat_id: int, msg: str):
        await cls._send(chat_id, f"💡 {msg}")

    @classmethod
    async def success(cls, chat_id: int, msg: str):
        await cls._send(chat_id, f"✅ {msg}")

    @classmethod
    async def warning(cls, chat_id: int, msg: str):
        await cls._send(chat_id, f"⚠️ {msg}")
