# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-01-09 16:25:11
# ============================================================

__generated__ = True
import os
from decimal import ROUND_DOWN, Decimal
from typing import Any

from openrouter import OpenRouter
from openrouter.components import ChatGenerationTokenUsage
from openrouter.operations import (
    CreateKeysResponse,
    GetKeyResponse,
)
from tortoise.exceptions import DoesNotExist
from tortoise.expressions import F
from tortoise.transactions import in_transaction

from app.common.models.orm import AiModel, User
from app.common.utils.usd_rate import get_usd_rate
from app.config import config

DEFAULT_MODEL = "openai/gpt-5.2-chat"
GENERATE_PROMPT_MODEL = "anthropic/claude-sonnet-4.5"


_MODEL_IDS = """
google/gemini-3-flash-preview
openai/gpt-5.2-chat
deepseek/deepseek-v3.2
x-ai/grok-4.1-fast
google/gemini-3-pro-preview
openai/gpt-5.1-chat
anthropic/claude-haiku-4.5
anthropic/claude-sonnet-4.5
google/gemini-2.5-flash-preview-09-2025
openai/gpt-5-mini
x-ai/grok-4-fast
google/gemini-2.5-flash-lite-preview-09-2025
google/gemini-2.5-pro
anthropic/claude-sonnet-4
openai/gpt-4.1
openai/gpt-4.1-mini
google/gemini-2.0-flash-lite-001
google/gemini-2.0-flash-001
anthropic/claude-3.5-sonnet
openai/chatgpt-4o-latest
openai/gpt-4o-mini
xiaomi/mimo-v2-flash:free
nex-agi/deepseek-v3.1-nex-n1:free
""".strip().splitlines()


DEFAULT_MODEL = "openai/gpt-5.2-chat"
GENERATE_PROMPT_MODEL = "anthropic/claude-sonnet-4.5"


class AiError(Exception):
    pass


class InsufficientBalance(AiError):
    pass


class ModelNotFound(AiError):
    pass


class OpenRouterKeyError(AiError):
    pass


class OpenRouterResponseError(AiError):
    pass


async def create_response(
    user: User, input: Any, max_tokens: int = 3000, timeout_min: int = 5
) -> str:
    # атомарно добавляем ключ/модель
    user = await add_openrouter_to_user(user)

    model = await get_ai_model(user.or_model)
    usd_rate = await get_usd_rate()

    await check_balance_before_request(user, model, max_tokens, usd_rate)

    try:
        os.environ["ALL_PROXY"] = config.openrouter.proxy
        async with OpenRouter(api_key=user.or_api_key) as app:
            response = await app.chat.send_async(
                model=user.or_model,
                messages=input,
                max_tokens=max_tokens,
                timeout_ms=timeout_min * 60 * 1000,
            )
    except Exception as e:
        raise OpenRouterResponseError(f"Ошибка запроса к OpenRouter: {e}") from e
    finally:
        os.environ.pop("ALL_PROXY", None)

    if not response or not response.choices:
        raise OpenRouterResponseError("Пустой ответ от AI")

    message = response.choices[0].message
    content = message.content
    usage = response.usage

    if not usage:
        raise OpenRouterResponseError("Нет usage в ответе")

    # атомарное списание баланса
    await charge_user_for_usage(user, model, usage, usd_rate)

    return str(content)


async def generate_prompt(user: User, metaprompt: str, timeout_min: int = 10) -> str:
    user = await add_openrouter_to_user(user)

    model = await get_ai_model(GENERATE_PROMPT_MODEL)
    usd_rate = await get_usd_rate()

    estimated_tokens = 20000
    await check_balance_before_request(user, model, estimated_tokens, usd_rate)

    try:
        os.environ["ALL_PROXY"] = config.openrouter.proxy
        async with OpenRouter(api_key=user.or_api_key) as app:
            response = await app.chat.send_async(
                model=model.id,
                messages=[{"role": "user", "content": metaprompt}],
                timeout_ms=timeout_min * 60 * 1000,
            )
    except Exception as e:
        raise OpenRouterResponseError(f"Ошибка запроса к OpenRouter: {e}") from e
    finally:
        os.environ.pop("ALL_PROXY", None)

    if not response or not response.choices:
        raise OpenRouterResponseError("Пустой ответ от AI")

    message = response.choices[0].message
    content = message.content
    usage = response.usage

    if usage:
        await charge_user_for_usage(user, model, usage, usd_rate)

    return str(content)


# ----------------- ПОТОКОБЕЗОПАСНЫЕ ВСПОМОГАТЕЛЬНЫЕ -----------------


async def add_openrouter_to_user(user: User) -> User:
    """
    Потокобезопасное добавление модели и API ключа OpenRouter.
    Используем транзакцию и select_for_update.
    """
    async with in_transaction() as conn:
        try:
            # блокируем пользователя для обновления
            db_user = (
                await User.filter(id=user.id).using_db(conn).select_for_update().get()
            )
        except DoesNotExist:
            raise ValueError(f"Пользователь с id={user.id} не найден")

        changed = False

        if not db_user.or_model:
            db_user.or_model = DEFAULT_MODEL
            changed = True

        if not db_user.or_api_key:
            try:
                key = await create_key(db_user.display_name)
            except Exception as e:
                raise OpenRouterKeyError("Не удалось создать API ключ") from e

            db_user.or_api_key = key.key
            db_user.or_api_hash = key.data.hash
            changed = True

        if changed:
            await db_user.save(update_fields=["or_model", "or_api_key", "or_api_hash"])

        return db_user


async def charge_user_for_usage(
    user: User,
    model: AiModel,
    usage: ChatGenerationTokenUsage,
    usd_rate: Decimal,
):
    prompt_cost = model.prompt_price * Decimal(usage.prompt_tokens or 0)
    completion_cost = model.completion_price * Decimal(usage.completion_tokens or 0)

    total_usd = (prompt_cost + completion_cost) * Decimal("1.1")
    total_rub = total_usd * usd_rate
    total_cents = int(total_rub * 100)

    if total_cents <= 0:
        return

    updated = await User.filter(id=user.id, balance__gte=total_cents).update(
        balance=F("balance") - total_cents
    )
    if not updated:
        raise InsufficientBalance("Недостаточно средств для списания")


async def check_balance_before_request(
    user: User, model: AiModel, max_tokens: int, usd_rate: Decimal
):
    estimated_cost_usd = (model.completion_price * Decimal(max_tokens)) * Decimal("1.1")
    estimated_cost_rub = estimated_cost_usd * usd_rate
    estimated_cost_cents = int(estimated_cost_rub * 100)

    if user.balance < estimated_cost_cents:
        needed_rub = Decimal(estimated_cost_cents) / Decimal(100)
        user_rub = Decimal(user.balance) / Decimal(100)
        raise InsufficientBalance(
            f"Недостаточно средств. Нужно ~{needed_rub:.2f} ₽, есть {user_rub:.2f} ₽"
        )


async def get_ai_model(or_model: str) -> AiModel:
    model = await AiModel.get_or_none(id=or_model)
    if not model:
        raise ModelNotFound(f"Модель {or_model} не найдена")
    return model


async def create_key(name: str) -> CreateKeysResponse:
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as app:
        key = await app.api_keys.create_async(name=name)
    return key


async def get_key(hash: str) -> GetKeyResponse:
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as app:
        key = await app.api_keys.get_async(hash=hash)
    return key


async def upsert_models():
    model_ids = await AiModel.all().values_list("id", flat=True)
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as app:
        response = await app.models.list_async()
        for model in response.data:
            if model.id not in model_ids:
                continue
            await AiModel.update_or_create(
                id=model.id,
                defaults={
                    "name": model.name,
                    # "description": model.description,
                    "prompt_price": Decimal(model.pricing.prompt),
                    "completion_price": Decimal(model.pricing.completion),
                },
            )


async def get_balance() -> Decimal:
    usd_rate = await get_usd_rate()
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as open_router:
        response = await open_router.credits.get_credits_async()

        balance_usd = Decimal(str(response.data.total_credits)) - Decimal(
            str(response.data.total_usage)
        )
        balance_rub = balance_usd * usd_rate
        return balance_rub.quantize(
            Decimal("0.00"),
            rounding=ROUND_DOWN,
        )
