# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-21 17:47:12
# ============================================================

__generated__ = True
import os
from decimal import Decimal
from typing import Any

from openrouter import OpenRouter
from openrouter.operations import CreateKeysResponse, GetKeyResponse
from tortoise.expressions import F

from app.common.models.orm import AiModel, User
from app.common.utils.usd_rate import get_usd_rate
from app.config import config

DEFAULT_MODEL = "openai/gpt-5.2-chat"
GENERATE_PROMPT_MODEL = "anthropic/claude-sonnet-4.5"


MODEL_IDS = """
google/gemini-3-flash-preview
openai/gpt-5.2-chat
deepseek/deepseek-v3.2
x-ai/grok-4.1-fast
google/gemini-3-pro-preview
openai/gpt-5.1-chat
anthropic/claude-haiku-4.5
anthropic/claude-sonnet-4.5
google/gemini-2.5-flash-preview-09-2025
openai/gpt-5-chat
openai/gpt-5-mini
openai/gpt-oss-120b:free
x-ai/grok-4-fast
google/gemini-2.5-flash-lite-preview-09-2025
x-ai/grok-4
google/gemini-2.5-pro
anthropic/claude-sonnet-4
openai/gpt-4.1
openai/gpt-4.1-mini
google/gemini-2.0-flash-lite-001
anthropic/claude-3.7-sonnet
google/gemini-2.0-flash-001
anthropic/claude-3.5-haiku
anthropic/claude-3.5-sonnet
openai/chatgpt-4o-latest
openai/gpt-4o-mini
deepseek/deepseek-r1-0528:free
""".strip().splitlines()


class AiError(Exception):
    pass


class InsufficientBalance(AiError):
    pass


class ModelNotFound(AiError):
    pass


class OpenRouterKeyError(AiError):
    pass


class OpenRouterResponseError(AiError):
    pass


async def create_response(
    user: User, input: Any, max_tokens: int = 350, timeout_min: int = 5
) -> str:
    await add_openrouter_to_user(user)
    model = await get_ai_model(user.or_model)
    usd_rate = await get_usd_rate()
    await check_balance_before_request(user, model, max_tokens, usd_rate)
    try:
        os.environ["ALL_PROXY"] = config.openrouter.proxy
        async with OpenRouter(api_key=user.or_api_key) as app:
            response = await app.chat.send_async(
                model=user.or_model,
                messages=input,
                max_tokens=max_tokens,
                timeout_ms=timeout_min * 60 * 1000,
            )
    except Exception as e:
        raise OpenRouterResponseError(f"Ошибка запроса к OpenRouter: {e}") from e
    finally:
        os.environ.pop("ALL_PROXY", None)

    if not response or not response.choices:
        raise OpenRouterResponseError("Пустой ответ от AI")

    message = response.choices[0].message
    content = message.content

    usage = response.usage
    if not usage:
        raise OpenRouterResponseError("Нет usage в ответе")

    await charge_user_for_usage(
        user=user,
        model=model,
        usage=usage,
        usd_rate=usd_rate,
    )

    return str(content)


async def generate_prompt(user: User, metaprompt: str, timeout_min: int = 10) -> str:
    """
    Формирует промпт и получает ответ от выбранного AI через OpenRouter.

    :param user: объект пользователя
    :param content: готовый текст промпта
    :param timeout_min: таймаут запроса в минутах
    :return: текст ответа AI
    """
    await add_openrouter_to_user(user)

    # используем модель пользователя, можно override при необходимости

    model = await get_ai_model(GENERATE_PROMPT_MODEL)

    usd_rate = await get_usd_rate()

    # проверяем баланс — ставим условный max_tokens для оценки, например 20000
    estimated_tokens = 20000
    await check_balance_before_request(user, model, estimated_tokens, usd_rate)

    try:
        os.environ["ALL_PROXY"] = config.openrouter.proxy
        async with OpenRouter(api_key=user.or_api_key) as app:
            response = await app.chat.send_async(
                model=model.id,
                messages=[{"role": "user", "content": metaprompt}],
                timeout_ms=timeout_min * 60 * 1000,
            )
    except Exception as e:
        raise OpenRouterResponseError(f"Ошибка запроса к OpenRouter: {e}") from e
    finally:
        os.environ.pop("ALL_PROXY", None)

    if not response or not response.choices:
        raise OpenRouterResponseError("Пустой ответ от AI")

    message = response.choices[0].message
    content = message.content
    usage = response.usage

    if not usage:
        # если usage нет, списываем фиксированную сумму
        await charge_user_for_usage(
            user=user,
            model=model,
            usage={"prompt_tokens": 0, "completion_tokens": 20000},  # пример
            usd_rate=usd_rate,
        )
    else:
        await charge_user_for_usage(
            user=user, model=model, usage=usage, usd_rate=usd_rate
        )

    return str(content)


async def add_openrouter_to_user(user: User):
    changed = False
    if not user.or_model:
        user.or_model = DEFAULT_MODEL
        changed = True

    if not user.or_api_key:
        try:
            key = await create_key(user.display_name)
        except Exception as e:
            raise OpenRouterKeyError("Не удалось создать API ключ") from e

        user.or_api_key = key.key
        user.or_api_hash = key.data.hash
        changed = True

    if changed:
        await user.save(update_fields=["or_model", "or_api_key", "or_api_hash"])


async def charge_user_for_usage(
    user: User,
    model: AiModel,
    usage,
    usd_rate: Decimal,
):
    prompt_cost = model.prompt_price * Decimal(usage.prompt_tokens)
    completion_cost = model.completion_price * Decimal(usage.completion_tokens)

    total_usd = (prompt_cost + completion_cost) * Decimal("1.1")
    total_rub = total_usd * usd_rate
    total_cents = int(total_rub * 100)

    if total_cents <= 0:
        return

    await User.filter(id=user.id, balance__gte=total_cents).update(
        balance=F("balance") - total_cents
    )


async def check_balance_before_request(
    user: User,
    model: AiModel,
    max_tokens: int,
    usd_rate: Decimal,
):
    estimated_cost_usd = (model.completion_price * Decimal(max_tokens)) * Decimal("1.1")
    estimated_cost_rub = estimated_cost_usd * usd_rate
    estimated_cost_cents = int(estimated_cost_rub * 100)

    if user.balance < estimated_cost_cents:
        # форматируем рубли и копейки
        needed_rub = Decimal(estimated_cost_cents) / Decimal(100)
        user_rub = Decimal(user.balance) / Decimal(100)
        raise InsufficientBalance(
            f"Недостаточно средств. Нужно ~{needed_rub:.2f} ₽, есть {user_rub:.2f} ₽"
        )


async def get_ai_model(or_model: str) -> AiModel:
    model = await AiModel.get_or_none(id=or_model)
    if not model:
        raise ModelNotFound(f"Модель {or_model} не найдена")
    return model


async def create_key(name: str) -> CreateKeysResponse:
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as app:
        key = await app.api_keys.create_async(name=name)
    return key


async def get_key(hash: str) -> GetKeyResponse:
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as app:
        key = await app.api_keys.get_async(hash=hash)
    return key


async def upsert_models():
    async with OpenRouter(api_key=config.openrouter.manager_api_key) as app:
        response = await app.models.list_async()
        for model in response.data:
            if model.id not in MODEL_IDS:
                continue
            await AiModel.update_or_create(
                id=model.id,
                defaults={
                    "name": model.name,
                    "description": model.description,
                    "prompt_price": Decimal(model.pricing.prompt),
                    "completion_price": Decimal(model.pricing.completion),
                },
            )
