# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-01 19:04:00
# ============================================================

__generated__ = True
import re

from app.common.models.enums import DialogStatus

PROMPT_TITLES = {
    "role": "РОЛЬ",
    "instruction": "ИНСТРУКЦИЯ",
    "context": "КОНТЕКСТ",
    "init": "STAGE 1: INIT",
    "engage": "STAGE 2: ENGAGE",
    "offer": "STAGE 3: OFFER",
    "closing": "STAGE 4: CLOSING",
    "transitions": "СИСТЕМА ПЕРЕХОДОВ МЕЖДУ STAGE",
    "rules": "ГЛОБАЛЬНЫЕ ПРАВИЛА",
}


def get_ooc_status(message: str) -> DialogStatus | None:
    match = re.search(r"STATUS:\s*(init|engage|offer|closing)", message)
    if match:
        status = match.group(1)
        return DialogStatus(status)


def strip_ooc_status(message: str) -> str:
    return re.sub(r"STATUS:.*", "", message).strip()


STATUS_ADDON = """
# СИСТЕМНАЯ ИНСТРУКЦИЯ

Текущий статус: {current_status}

После ответа добавь в конец строку:
STATUS: [init|engage|offer|closing]

Правила перехода:
- init → engage: пользователь назвал конкретное направление работы
- engage → offer: всегда переходи сразу (этап пропускается)
- offer → closing: пользователь согласился ("да", "давай", "интересно")
- closing → complete: собраны время И контакт

Если цель текущего статуса НЕ достигнута — верни текущий статус.
"""


def get_status_addon(status: DialogStatus) -> str:
    return STATUS_ADDON.replace("{current_status}", status.value)


async def build_prompt(prompt: dict, status: DialogStatus = DialogStatus.INIT):
    text = []
    statuses = {s.value for s in DialogStatus}
    for key, title in PROMPT_TITLES.items():
        if key not in statuses:
            block = f"# {title}\n{prompt[key]}"
            text.append(block)
        elif key == status:
            block = f"# {title}\n{prompt[key]}"
            text.append(block)

    markdown = "\n\n".join(text)
    markdown = markdown.replace("{current_status}", status.value)
    return markdown
