# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-22 22:34:37
# ============================================================

__generated__ = True
import re

from pydantic import BaseModel

from app.common.models.enums import DialogStatus
from app.common.models.orm import Account, AppSettings, Recipient


class ProjectSkipOptions(BaseModel):
    engage: bool
    offer: bool
    closing: bool


DEFAULT_SKIP_OPTIONS = ProjectSkipOptions(engage=False, offer=False, closing=False)


PROMPT_TITLES = {
    "role": "РОЛЬ",
    "instruction": "ИНСТРУКЦИЯ",
    "context": "КОНТЕКСТ",
    "init": "STAGE 1: INIT",
    "engage": "STAGE 2: ENGAGE",
    "offer": "STAGE 3: OFFER",
    "closing": "STAGE 4: CLOSING",
    "rules": "ГЛОБАЛЬНЫЕ ПРАВИЛА",
}


def get_ooc_status(message: str) -> DialogStatus | None:
    match = re.search(
        r"STATUS:\s*\[?(init|engage|offer|closing|negative|operator)\]?",
        message,
        re.IGNORECASE,
    )
    if match:
        return DialogStatus(match.group(1).lower())


def strip_ooc_status(message: str) -> str:
    return re.sub(
        r"STATUS:\s*\[?(init|engage|offer|closing|negative|operator)\]?",
        "",
        message,
        flags=re.IGNORECASE,
    ).strip()


async def get_status_addon() -> str:
    return await AppSettings.fetch("prompt.system")


def get_name_addon(account: Account, recipient: Recipient) -> str:
    addon = []
    account_names = [n for n in (account.first_name, account.last_name) if n]
    if any(account_names):
        addon.append(f"Тебя зовут {' '.join(account_names)}")

    recipient_names = [n for n in (recipient.first_name, recipient.last_name) if n]
    if any(recipient_names):
        addon.append(f"Твоего собеседника зовут {' '.join(recipient_names)}")

    return "\n".join(addon)


async def get_generator() -> str:
    return await AppSettings.fetch("prompt.generator")


def build_prompt(prompt: dict, status: DialogStatus = DialogStatus.INIT):
    text = []
    statuses = {s.value for s in DialogStatus}
    for key, title in PROMPT_TITLES.items():
        if key not in statuses:
            block = f"# {title}\n{prompt[key]}"
            text.append(block)
        elif key == status:
            block = f"# {title}\n{prompt[key]}"
            text.append(block)

    markdown = "\n\n".join(text)
    markdown = markdown.replace("{current_status}", status.value)
    return markdown


def build_prompt_v2(
    prompt: dict[str, str],
    status: str = DialogStatus.INIT,
    skip_options: ProjectSkipOptions = DEFAULT_SKIP_OPTIONS,
):
    # статусные ключи как строки
    statuses = {s.value for s in DialogStatus}  # {"init", "engage", "offer", "closing"}
    dynamic_order = ["engage", "offer", "closing"]

    # ищем первую доступную динамическую секцию
    active_status: str | None = None
    status_value = status.value if isinstance(status, DialogStatus) else status

    # INIT всегда включается, независимо от skip_options
    if status_value == "init":
        active_status = "init"
    elif status_value in dynamic_order:
        # Начинаем поиск с текущего статуса
        start_index = dynamic_order.index(status_value)
        for s in dynamic_order[start_index:]:
            # Проверяем, не пропущена ли эта секция
            is_skipped = getattr(skip_options, s, False)
            if not is_skipped:
                active_status = s
                break

    print(f"Status: {status_value}, Active: {active_status}")

    text = []
    for key, title in PROMPT_TITLES.items():
        if key not in statuses:
            # обычная секция
            block = f"# {title}\n{prompt[key]}"
            text.append(block)
        elif key == active_status:
            # динамическая секция, которая не пропущена
            block = f"# {title}\n{prompt[key]}"
            text.append(block)

    content = "\n\n".join(text)
    content = content.replace("{current_status}", status)
    return content
