# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-02 23:04:02
# ============================================================

__generated__ = True
import uuid
from dataclasses import asdict, dataclass
from datetime import timedelta
from enum import StrEnum
from typing import List, Optional

from tortoise import timezone as tz
from tortoise.transactions import in_transaction

from app.common.models.orm import Account, AccountStatus, Proxy
from app.common.utils.account import AccountUtil
from app.common.utils.proxy import ProxyUtil

LOCK_TIMEOUT = 30  # секунд, на сколько блокируем прокси


class Status(StrEnum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    SUCCESS = "success"


@dataclass
class ProxyLogEntry:
    status: Status
    message: str
    payload: Optional[dict] = None


class ProxyPool:
    """
    Пул прокси с ограничением по user_id.
    Один прокси может быть привязан только к одному аккаунту.
    Safe для многопроцессной и многопоточной работы.
    """

    MAX_FAILURES = 5

    def __init__(self, user_id: int):
        self.user_id = user_id
        self.logs: List[ProxyLogEntry] = []

    # ----------------- Логи -----------------
    def _add_log(self, status: Status, message: str, payload: Optional[dict] = None):
        self.logs.append(ProxyLogEntry(status=status, message=message, payload=payload))

    def get_logs(self, clear: bool = False) -> List[ProxyLogEntry]:
        logs_copy = self.logs.copy()
        if clear:
            self.clear_logs()
        return logs_copy

    def clear_logs(self):
        self.logs.clear()

    def get_logs_as_dicts(self, clear: bool = False) -> List[dict]:
        logs = [asdict(entry) for entry in self.logs]
        if clear:
            self.clear_logs()
        return logs

    # ----------------- Прокси для нового аккаунта -----------------
    async def acquire_for_account_loading(
        self, account: AccountUtil
    ) -> Optional[Proxy]:
        """
        Получить свободный прокси для аккаунта.
        Берём несколько доступных, проверяем по очереди и блокируем безопасно между воркерами.
        """
        now = tz.now()
        session_id = str(uuid.uuid4())
        LIMIT = 5  # сколько прокси брать за раз

        async with in_transaction() as conn:
            # Берём несколько доступных прокси, которых никто не использует
            rows = await conn.execute_query_dict(
                """
                SELECT p.*
                FROM proxies p
                LEFT JOIN accounts a ON a.proxy_id = p.id
                WHERE p.user_id = $1
                AND p.active = TRUE
                AND p.country = $2
                AND a.id IS NULL
                AND (p.locked_until IS NULL OR p.locked_until < $3)
                ORDER BY p.failures ASC
                LIMIT $4
                FOR UPDATE
                """,
                [self.user_id, account.country, now, LIMIT],
            )

            if not rows:
                self._add_log(
                    Status.ERROR,
                    "No available proxies for user/country",
                    {"user_id": self.user_id, "country": account.country},
                )
                return None

            for row in rows:
                # Загружаем объект Proxy из строки
                proxy = await Proxy(**row)
                proxy._saved_in_db = True
                # Блокируем прокси на время проверки
                proxy.locked_until = now + timedelta(seconds=LOCK_TIMEOUT)
                proxy.lock_session = session_id
                await proxy.save(
                    update_fields=["locked_until", "lock_session"], using_db=conn
                )

                try:
                    proxy_util = ProxyUtil.from_orm(proxy)
                    if await proxy_util.check():
                        # Очистка блокировки после успешной проверки
                        proxy.locked_until = None  # type: ignore
                        proxy.lock_session = None  # type: ignore
                        await proxy.save(
                            update_fields=["locked_until", "lock_session"],
                            using_db=conn,
                        )

                        self._add_log(
                            Status.SUCCESS,
                            "Proxy successfully checked for account",
                            {"proxy_id": proxy.id, "account_phone": account.phone},
                        )
                        return proxy
                    else:
                        await self._handle_proxy_failure(proxy)
                except Exception as e:
                    await self._handle_proxy_failure(proxy)
                    self._add_log(
                        Status.ERROR,
                        f"Error checking proxy: {type(e).__name__}: {e}",
                        {"proxy_id": proxy.id},
                    )
                finally:
                    # Освобождаем блокировку, если проверка не удалась
                    if proxy.lock_session == session_id:  # только свой lock снимаем
                        proxy.locked_until = None  # type: ignore
                        proxy.lock_session = None  # type: ignore
                        await proxy.save(
                            update_fields=["locked_until", "lock_session"],
                            using_db=conn,
                        )

        self._add_log(
            Status.ERROR,
            "All available proxies failed checks",
            {"user_id": self.user_id, "country": account.country},
        )
        return None

    # ----------------- Проверка привязанного прокси -----------------
    async def verify_account_proxy(self, account: Account) -> bool:
        """
        Проверить привязанный к аккаунту прокси.
        """
        if not account.proxy:
            self._add_log(
                Status.WARNING,
                "Account has no proxy assigned",
                {"account_id": account.id},
            )
            return False

        proxy = account.proxy
        if not proxy.active:
            await self._deactivate_account(account)
            return False

        try:
            proxy_model = ProxyUtil.from_orm(proxy)
            if await proxy_model.check():
                if proxy.failures > 0:
                    old_failures = proxy.failures
                    proxy.failures -= 1
                    await proxy.save(update_fields=["failures"])
                    self._add_log(
                        Status.INFO,
                        "Proxy check successful, failures decreased",
                        {
                            "proxy_id": proxy.id,
                            "account_id": account.id,
                            "old_failures": old_failures,
                            "failures": proxy.failures,
                        },
                    )
                else:
                    self._add_log(
                        Status.INFO,
                        "Proxy check successful",
                        {"proxy_id": proxy.id, "account_id": account.id, "failures": 0},
                    )
                return True
            else:
                await self._handle_proxy_failure(proxy)
                if not proxy.active:
                    await self._deactivate_account(account)
                return False
        except Exception as e:
            self._add_log(
                Status.ERROR,
                f"Error checking proxy for account: {type(e).__name__}: {e}",
                {"proxy_id": proxy.id, "account_id": account.id},
            )
            await self._handle_proxy_failure(proxy)
            return False

    # ----------------- Гарантия рабочего прокси -----------------
    async def ensure_account_has_working_proxy(
        self, account: Account
    ) -> Optional[Proxy]:
        """
        Гарантировать, что у аккаунта есть рабочий прокси.
        Возвращает:
            Proxy — рабочий прокси для использования
            None — если не удалось получить рабочий прокси
        """
        if not account.proxy:
            self._add_log(
                Status.INFO,
                "Account has no proxy, assigning...",
                {"account_id": account.id},
            )
            proxy = await self.acquire_for_account_loading(
                await AccountUtil.from_orm(account)
            )
            if not proxy:
                self._add_log(
                    Status.ERROR,
                    "No proxy available to assign",
                    {"account_id": account.id},
                )
                return None

            account.proxy = proxy
            await account.save(update_fields=["proxy_id"])

            await self.release_proxy_lock(proxy)

            self._add_log(
                Status.SUCCESS,
                "Proxy assigned to account",
                {"account_id": account.id, "proxy_id": proxy.id},
            )
            return proxy

        # Если прокси есть, проверяем
        if await self.verify_account_proxy(account):
            return account.proxy
        return None

    # ----------------- Обработка неудачной проверки -----------------
    async def _handle_proxy_failure(self, proxy: Proxy):
        old_failures = proxy.failures
        proxy.failures += 1
        self._add_log(
            Status.WARNING,
            "Proxy failed check",
            {
                "proxy_id": proxy.id,
                "old_failures": old_failures,
                "failures": proxy.failures,
            },
        )
        if proxy.failures >= self.MAX_FAILURES:
            proxy.active = False
            self._add_log(
                Status.ERROR,
                "Proxy deactivated due to failures",
                {"proxy_id": proxy.id, "failures": proxy.failures},
            )
        await proxy.save(update_fields=["failures", "active"])

    # ----------------- Деактивация аккаунта -----------------
    async def _deactivate_account(self, account: Account):
        account.active = False
        account.status = AccountStatus.NOPROXY
        await account.save(update_fields=["active", "status"])
        self._add_log(
            Status.WARNING,
            "Account deactivated: proxy is inactive",
            {"account_id": account.id, "proxy_id": account.proxy_id},
        )

    async def release_proxy_lock(self, proxy: Proxy):
        """Снять блокировку с прокси после привязки к аккаунту"""
        proxy.locked_until = None  # type: ignore
        proxy.lock_session = None  # type: ignore
        await proxy.save(update_fields=["locked_until", "lock_session"])
        self._add_log(
            Status.INFO,
            "Proxy lock released after account binding",
            {"proxy_id": proxy.id},
        )
