name: neurogram-prod

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: neuro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neurogram
    ports:
      - "5445:5432" # доступ с хоста (ноута)
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - dev

  pg-backup:
    image: pgvector/pgvector:pg15
    container_name: neuro-postgres-backup
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGPASSWORD: postgres
    volumes:
      - /root/db_backups/neurogram:/backups
    networks:
      - dev
    command: >
      bash -c "
      while true; do
        TODAY=\"/backups/backup_$$(date +%Y-%m-%d).sql.gz\";
        if [ ! -f \"$$TODAY\" ]; then
          echo \"[$$(date)] Running daily backup...\";
          pg_dump -h postgres -U postgres -d neurogram -F p | gzip > \"$$TODAY\";
          find /backups -type f -mtime +7 -delete;
        fi;
        sleep 3600;
      done
      "

  base:
    build:
      context: ../..
      dockerfile: app/workers/base/Dockerfile
      target: prod
    container_name: neuro-base
    volumes:
      - ../../app:/app
      - uv-venv-base:/app/.venv # отдельный том под venv worker
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
      - UV_LINK_MODE=copy
    command: ["uv", "run", "python", "-m", "workers.base"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - s3

  dialog:
    build:
      context: ../..
      dockerfile: app/workers/dialog/Dockerfile
      target: prod
    volumes:
      - ../../app:/app
      - uv-venv-dialog:/app/.venv # отдельный том под venv worker
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
      - UV_LINK_MODE=copy
    command: ["uv", "run", "python", "-m", "workers.dialog"]
    depends_on:
      - postgres
    networks:
      - hatchet
      - dev
      - s3
    deploy:
      replicas: 5

  api:
    build:
      context: ../..
      dockerfile: app/api/Dockerfile
      target: prod
    container_name: neuro-api
    volumes:
      - ../../app:/app
      - uv-venv-api:/app/.venv # отдельный том под venv api
      - ./config.yml:/app/config.yml
    environment:
      - UV_SYSTEM_PYTHON=1
      - PYTHONPATH=/app
    command: ["uv", "run", "python", "-m", "api"]
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:18833:8833"
    networks:
      - hatchet
      - dev

  web:
    build:
      context: ../..
      dockerfile: web/Dockerfile.prod
    container_name: neuro-web
    depends_on:
      - api
      - base-worker
    ports:
      - "127.0.0.1:13000:3000"
    networks:
      - dev

  minio:
    build:
      context: ./minio
    container_name: neuro-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: b23vk6N1VdOV
      # Эти переменные нужны для правильной работы MinIO через reverse proxy
      MINIO_SERVER_URL: "https://media.cybcom.online"
      MINIO_BROWSER_REDIRECT_URL: "https://minio.cybcom.online"
      S3_ACCESS_KEY: "IhDRQQH1TfL0wQtUDpKV"
      S3_SECRET_KEY: "G2J10kVTv3E6eBMHOcmnQIrM00fqwa3fFpqCs49g"
    ports:
      - "127.0.0.1:19100:9000"
      - "127.0.0.1:19101:9001"
    volumes:
      - minio-data:/data
    networks:
      - dev

volumes:
  uv-venv-base: {}
  uv-venv-dialog: {}
  uv-venv-api: {}
  postgres-data-dev:
    name: prod_postgres-data-dev

networks:
  hatchet:
    external: true
    name: hatchet-network
  dev:
    name: dev
    driver: bridge
  s3:
    external: true
    name: neuro-s3-prod
