# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-02-21 17:22:12
# ============================================================

__generated__ = True


from typing import Literal, Optional
from pydantic import BaseModel
from typing import Optional
from typing import Literal

class BuyPremiumOut(BaseModel):
    status: Literal['error', 'success']
    message: Optional[str] = None
    verification_url: Optional[str] = None


class DialogIn(BaseModel):
    account_id: int
    recipients_id: list[int]
    key: str


class GeneratePromptIn(BaseModel):
    project_id: int


class SynonimizeIn(BaseModel):
    user_id: int
    text: str


class AccountsCheckIn(BaseModel):
    ids: list[int]


class ProjectDocument(BaseModel):
    filename: str
    file_size: int
    storage_path: str
    content_type: str


class ProjectDocumentsIn(BaseModel):
    project_id: int
    documents: list[ProjectDocument]


class SynonimizeOut(BaseModel):
    text: str
    error: Optional[str] = None


class ProxiesUploadIn(BaseModel):
    user_id: int
    proxies: list[str]


class CardDetails(BaseModel):
    number: str
    month: int
    year: int
    cvv: str


class AccountsUpdatePhotosIn(BaseModel):
    delete: list[int]
    upload: list[str]


class AccountsUpdateIn(BaseModel):
    id: int
    user_id: int
    username: str | None
    about: str | None
    channel: str | None
    first_name: str | None
    last_name: str | None
    photos: AccountsUpdatePhotosIn


class ProxiesCheckIn(BaseModel):
    ids: list[int]


class StopPremiumIn(BaseModel):
    account_id: int


class BuyPremiumIn(BaseModel):
    account_id: int
    card: CardDetails


class AccountsUploadIn(BaseModel):
    user_id: int
    s3path: str


class AccountsGenerateIn(BaseModel):
    ids: list[int]
    gender: Literal['any', 'male', 'female'] = 'any'
    generate_names: bool = True
    generate_usernames: bool = True
