# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-02-21 17:22:12
# ============================================================

__generated__ = True


from . import models
from api.hatchet.client import hatchet

accounts_check = hatchet.stubs.task(
    name="accounts-check",
    input_validator=models.AccountsCheckIn,
)

stop_premium = hatchet.stubs.task(
    name="stop-premium",
    input_validator=models.StopPremiumIn,
)

accounts_generate = hatchet.stubs.task(
    name="accounts-generate",
    input_validator=models.AccountsGenerateIn,
)

buy_premium = hatchet.stubs.task(
    name="buy-premium",
    input_validator=models.BuyPremiumIn,
    output_validator=models.BuyPremiumOut,
)

accounts_update = hatchet.stubs.task(
    name="accounts-update",
    input_validator=models.AccountsUpdateIn,
)

accounts_upload = hatchet.stubs.task(
    name="accounts-upload",
    input_validator=models.AccountsUploadIn,
)

save_documents = hatchet.stubs.task(
    name="save_documents",
    input_validator=models.ProjectDocumentsIn,
)

dialog = hatchet.stubs.task(
    name="dialog",
    input_validator=models.DialogIn,
)

generate_prompt = hatchet.stubs.task(
    name="generate-prompt",
    input_validator=models.GeneratePromptIn,
)

proxies_check = hatchet.stubs.task(
    name="proxies-check",
    input_validator=models.ProxiesCheckIn,
)

proxies_upload = hatchet.stubs.task(
    name="proxies-upload",
    input_validator=models.ProxiesUploadIn,
)

synonimize = hatchet.stubs.task(
    name="synonimize",
    input_validator=models.SynonimizeIn,
    output_validator=models.SynonimizeOut,
)
