# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-02-21 17:22:12
# ============================================================

__generated__ = True


from . import models
from api.hatchet.client import hatchet

heartbeat = hatchet.stubs.workflow(
    name="heartbeat",
)

nightly = hatchet.stubs.workflow(
    name="nightly",
)
