import json
import re
import tomllib
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ValidationError, field_validator, model_validator
from rich import print

header = f"""# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# ============================================================

__generated__ = True
"""


class CodegenConfig(BaseModel):
    worker_module: str
    output_dir: Path
    client_import: str
    client_name: str | None = None
    header: str = header

    @model_validator(mode="before")
    @classmethod
    def validate_and_set_client_name(cls, data: dict[str, Any]) -> dict[str, Any]:
        if isinstance(data, dict):
            if "client_import" in data:
                pattern = r"^from\s+[\w\.]+\s+import\s+(\w+)(?:\s+as\s+(\w+))?$"
                match = re.match(pattern, data["client_import"].strip())
                if not match:
                    raise ValueError(
                        f"Неверный формат импорта: {data['client_import']}"
                    )

                # Устанавливаем client_name только если он не задан
                if data.get("client_name") is None:
                    data["client_name"] = match.group(2) or match.group(1)

        return data

    @field_validator("worker_module")
    def validate_worker_module(cls, v: str) -> str:
        pattern = r"^[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*$"
        if not re.match(pattern, v):
            raise ValueError(
                f"Неверный формат модуля: {v}. "
                "Ожидается формат типа 'app.worker' или 'package.subpackage.module'"
            )
        return v


@dataclass
class TaskData:
    name: str
    input_model: type[Any] | None
    output_model: type[Any] | None


@dataclass
class WorkflowData:
    name: str
    input_model: type[Any] | None


@dataclass
class StubsData:
    tasks: list[TaskData]
    workflows: list[WorkflowData]


class ModulesConfig(BaseModel):
    src: Path
    dest: Path
    modules: list[str]


class SyncConfig(BaseModel):
    codegen: CodegenConfig
    modules: ModulesConfig


def get_config():
    with open("pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    try:
        return SyncConfig(**data["tool"]["sync"])
    except ValidationError as e:
        print("❌ Ошибка валидации секции [tool.sync]:")
        for err in e.errors():
            loc = ".".join(str(x) for x in err["loc"])
            msg = err["msg"]
            print(f"  • {loc}: {msg}")
        raise SystemExit(1)
