# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-09-21 21:16:42
# ============================================================

__generated__ = True


from pydantic import BaseModel

class AccountsUploadIn(BaseModel):
    user_id: int
    s3path: str


class AccountsUpdatePhotosIn(BaseModel):
    delete: list[int]
    upload: list[str]


class AccountsUpdateIn(BaseModel):
    id: int
    user_id: int
    username: str | None
    about: str | None
    channel: str | None
    first_name: str | None
    last_name: str | None
    photos: AccountsUpdatePhotosIn


class ProxiesUploadIn(BaseModel):
    user_id: int
    s3path: str
