# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-12-24 21:32:04
# ============================================================

__generated__ = True


from pydantic import BaseModel
from typing import Optional
from typing import Literal, Optional

class ProxiesUploadIn(BaseModel):
    user_id: int
    proxies: list[str]


class AccountsCheckIn(BaseModel):
    ids: list[int]


class GeneratePromptIn(BaseModel):
    project_id: int


class AccountsUpdatePhotosIn(BaseModel):
    delete: list[int]
    upload: list[str]


class SynonimizeIn(BaseModel):
    user_id: int
    text: str


class AccountsUpdateIn(BaseModel):
    id: int
    user_id: int
    username: str | None
    about: str | None
    channel: str | None
    first_name: str | None
    last_name: str | None
    photos: AccountsUpdatePhotosIn


class StopPremiumIn(BaseModel):
    account_id: int


class CardDetails(BaseModel):
    number: str
    month: int
    year: int
    cvv: str


class SynonimizeOut(BaseModel):
    text: str
    error: Optional[str] = None


class BuyPremiumIn(BaseModel):
    account_id: int
    card: CardDetails


class AccountsUploadIn(BaseModel):
    user_id: int
    s3path: str


class BuyPremiumOut(BaseModel):
    status: Literal['error', 'success']
    message: Optional[str] = None
    verification_url: Optional[str] = None
