# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2026-03-07 15:46:28
# ============================================================

__generated__ = True


from . import models
from app.hatchet.client import hatchet

proxies_upload = hatchet.stubs.task(
    name="proxies-upload",
    input_validator=models.ProxiesUploadIn,
)

accounts_upload = hatchet.stubs.task(
    name="accounts-upload",
    input_validator=models.AccountsUploadIn,
)

accounts_upload_mp = hatchet.stubs.task(
    name="accounts-upload-mp",
    input_validator=models.AccountsUploadIn,
)

accounts_update = hatchet.stubs.task(
    name="accounts-update",
    input_validator=models.AccountsUpdateIn,
)

accounts_update_mp = hatchet.stubs.task(
    name="accounts-update-mp",
    input_validator=models.AccountsUpdateIn,
)

accounts_check = hatchet.stubs.task(
    name="accounts-check",
    input_validator=models.AccountsCheckIn,
)

accounts_check_mp = hatchet.stubs.task(
    name="accounts-check-mp",
    input_validator=models.AccountsCheckIn,
)

proxies_check = hatchet.stubs.task(
    name="proxies-check",
    input_validator=models.ProxiesCheckIn,
)

buy_premium = hatchet.stubs.task(
    name="buy-premium",
    input_validator=models.BuyPremiumIn,
    output_validator=models.BuyPremiumOut,
)

buy_premium_mp = hatchet.stubs.task(
    name="buy-premium-mp",
    input_validator=models.BuyPremiumIn,
    output_validator=models.BuyPremiumOut,
)

generate_prompt = hatchet.stubs.task(
    name="generate-prompt",
    input_validator=models.GeneratePromptIn,
)

synonimize = hatchet.stubs.task(
    name="synonimize",
    input_validator=models.SynonimizeIn,
    output_validator=models.SynonimizeOut,
)

stop_premium = hatchet.stubs.task(
    name="stop-premium",
    input_validator=models.StopPremiumIn,
)

stop_premium_mp = hatchet.stubs.task(
    name="stop-premium-mp",
    input_validator=models.StopPremiumIn,
)
