# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-11-14 20:59:05
# ============================================================

__generated__ = True


from . import models
from app.hatchet.client import hatchet

proxies_upload = hatchet.stubs.task(
    name="proxies-upload",
    input_validator=models.ProxiesUploadIn,
)

accounts_upload = hatchet.stubs.task(
    name="accounts-upload",
    input_validator=models.AccountsUploadIn,
)

accounts_update = hatchet.stubs.task(
    name="accounts-update",
    input_validator=models.AccountsUpdateIn,
)

accounts_check = hatchet.stubs.task(
    name="accounts-check",
    input_validator=models.AccountsCheckIn,
)

buy_premium = hatchet.stubs.task(
    name="buy-premium",
    input_validator=models.BuyPremiumIn,
    output_validator=models.BuyPremiumOut,
)
