# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-10-31 21:03:50
# ============================================================

__generated__ = True


from . import models
from app.hatchet.client import hatchet

proxies_upload = hatchet.stubs.task(
    name="proxies-upload",
    input_validator=models.ProxiesUploadIn,
)

accounts_upload = hatchet.stubs.task(
    name="accounts-upload",
    input_validator=models.AccountsUploadIn,
)

accounts_update = hatchet.stubs.task(
    name="accounts-update",
    input_validator=models.AccountsUpdateIn,
)

buy_premium = hatchet.stubs.task(
    name="buy-premium",
    input_validator=models.BuyPremiumIn,
)
