# ============================================================
# !!! WARNING: This file is auto-generated by stub_codegen !!!
# !!! Do not edit manually. Any changes will be overwritten !!!
# Generated on: 2025-10-31 21:03:50
# ============================================================

__generated__ = True

from . import models
from app.hatchet.client import hatchet

heartbeat = hatchet.stubs.workflow(
  name="heartbeat",
)
