/// <reference types="vite/client" />

/** generated by vite-plugin-runtime */
interface ImportMetaEnv {
  readonly API_URL: string;
  readonly USERS_URL: string;
  readonly BOT_NAME: string;
  readonly WEB_URL: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
