/// <reference types="vite/client" />

/** generated by vite-plugin-runtime */
interface ImportMetaEnv {
  readonly API_URL: string;
  readonly MOCK_LOGIN: number;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
